Repository nnaisense/evotorch, pull requests merged in 2022-11, with the labels that each got.

#35 Implementation of WandbLogger
  src/evotorch/logging.py
Labels: enhancement

#39 fix: Fix all the mkdocstrings warnings
  src/evotorch/algorithms/distributed/gaussian.py
  src/evotorch/core.py
  src/evotorch/neuroevolution/net/statefulmodule.py
  src/evotorch/neuroevolution/net/vecrl.py
  src/evotorch/tools/misc.py
  src/evotorch/tools/objectarray.py
Labels: bug, documentation

#37 docs: Update the logging page and add WandbLogger section
  docs/examples/index.md
  docs/gen_doc_stubs.py
  docs/user_guide/logging.md
  examples/scripts/rl_clipup.py
  mkdocs.yml
  setup.cfg
  src/evotorch/logging.py
Labels: documentation

#38 feat: Simplify the usage of NeptuneLogger
  docs/user_guide/logging.md
  src/evotorch/logging.py
Labels: enhancement

#32 GPU-friendly + vectorized pareto ranking
  src/evotorch/core.py
  src/evotorch/operators/base.py
  tests/test_core.py
  tests/test_pareto_sorting.py
Labels: enhancement
