Repository nnaisense/evotorch, pull requests merged in 2022-10, with the labels that each got.

#21 Cloning and serialization improvements
  src/evotorch/core.py
  src/evotorch/distributions.py
  src/evotorch/tools/__init__.py
  src/evotorch/tools/cloning.py
  src/evotorch/tools/immutable.py
  src/evotorch/tools/misc.py
  src/evotorch/tools/objectarray.py
  src/evotorch/tools/readonlytensor.py
  src/evotorch/tools/recursiveprintable.py
  tests/test_cloning.py
  tests/test_core.py
  tests/test_objectarray.py
  tests/test_tensors_in_container.py
Labels: bug, enhancement

#26 Add pre-commit.ci
  README.md
  docs/user_guide/gym.md
  src/evotorch/neuroevolution/neproblem.py
  src/evotorch/neuroevolution/vecgymne.py
  src/evotorch/tools/__init__.py
  src/evotorch/tools/misc.py
Labels: documentation

#27 Add pass_info decorator
  docs/user_guide/gym.md
  examples/notebooks/Model_Predictive_Control_with_CEM/reacher_mpc.ipynb
  examples/scripts/rl_enjoy.py
  pyproject.toml
  setup.cfg
  src/evotorch/__init__.py
  src/evotorch/decorators.py
  src/evotorch/neuroevolution/gymne.py
  src/evotorch/neuroevolution/neproblem.py
  src/evotorch/neuroevolution/vecgymne.py
  src/evotorch/tools/__init__.py
  src/evotorch/tools/misc.py
  src/evotorch/tools/readonlytensor.py
  src/evotorch/tools/versionchecking.py
  tests/test_tools_misc.py
  tests/test_versionchecking.py
Labels: enhancement

#28 Update documentation of GPU usage with ray
  docs/user_guide/problem_parallelization.md
Labels: documentation

#31 docs: Update docs and examples related to GymNE
  README.md
  docs/advanced_usage/custom_ea.md
  docs/advanced_usage/dist_based.md
  docs/user_guide/gym.md
  examples/notebooks/Brax_Experiments_with_PGPE.ipynb
  examples/notebooks/Gym_Experiments_with_PGPE_and_CoSyNE.ipynb
  examples/scripts/rl_clipup.py
  examples/scripts/rl_gym.py
Labels: documentation
