Repository nnaisense/evotorch, pull requests merged in 2023-01, with the labels that each got.

#40 chore: Add noxfile to run pytest across multiple python versions
  .gitignore
  noxfile.py
  setup.cfg
Labels: enhancement

#48 feat: Add env. variable to control verbosity of the logger
  src/evotorch/__init__.py
  src/evotorch/tools/misc.py
Labels: enhancement

#55 fix: Make `center_init` of `CMAES` accept `Solution` instances
  src/evotorch/algorithms/cmaes.py
Labels: bug

#57 Update readme.md to include CMA-ES
  README.md
Labels: documentation
